### ISSUE TITLE
Envelope cannot be searialized to JSON

### ISSUE THREAD

**Issue by jimidle** [jhillyerd/enmime#205] opened 2021-08-01 08:20 UTC
What I did:

Standard `json.Marshall()` 

What I expected:

JSON representation of the envelope

What I got:

JSON error indicating that the struct contains circular arguments. This is because the Parent filed of a Part points back up the chain and does indeed cause a circular reference. Could be fixed by using JSON annotations to ignore the Parent field. Maybe add a func to rebuild those fields after UnMarshal - maybe best way would be to provide helper funcs to Marshall and UnMarshall and take care of Parent references automatically.

Sometimes, with microservices, there is no option but to use JSON to pass around the parsed email.

Release or branch I am using:

	github.com/jhillyerd/enmime v0.9.0

(Please attach a sample message if you feel it will help reproduce the issue)

Use any email with attachments of some kind.

**Comment by jhillyerd** [comment] 2021-08-01 15:47
Duplicate of #146

**Closed by jhillyerd** 2021-08-01 15:47 UTC
